# Waveshare ESP32-S3-Touch-LCD-7: ESP32-S3R8 (8MB octal PSRAM, 8MB flash) + 800x480 RGB panel (ST7262)
set(IDF_TARGET esp32s3)

# No sdkconfig.ble: BLE is not used, and it costs internal RAM.
set(SDKCONFIG_DEFAULTS
    boards/sdkconfig.base
    boards/sdkconfig.spiram_quad
    boards/sdkconfig.240mhz
    boards/sdkconfig.spiram_oct
    boards/sdkconfig.flash_qio_80m
    ${CMAKE_CURRENT_LIST_DIR}/sdkconfig.board
    ${CMAKE_CURRENT_LIST_DIR}/sdkconfig.paths   # generated by build.sh (absolute partition table path)
)

list(APPEND MICROPY_DEF_BOARD
    MICROPY_HW_BOARD_NAME="Waveshare ESP32-S3-Touch-LCD-7"
    MICROPY_PY_BLUETOOTH=0
)
