#!/usr/bin/env python3
"""Regenerate py/core/certs.py: the root CA certificates the updater trusts (GitHub's API and release download hosts).

    python3 scripts/gen_certs.py [/path/to/ca-bundle.pem]

Roots are taken from the system bundle by subject name; edit WANTED to change the set. The board verifies GitHub's TLS
certificate chain against these only (no system store on the device), so keep the list current if GitHub changes CAs.
"""
import os
import re
import subprocess
import sys

WANTED = (
    "USERTrust ECC Certification Authority",      # api.github.com / github.com (via Sectigo)
    "USERTrust RSA Certification Authority",
    "ISRG Root X1",                                # release-assets.githubusercontent.com (Let's Encrypt)
    "ISRG Root X2",
    "DigiCert Global Root G2",                     # GitHub's previous CA, kept for fallback
)
BUNDLES = ("/etc/pki/tls/certs/ca-bundle.crt", "/etc/ssl/certs/ca-certificates.crt")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "py", "core", "certs.py")


def subject(pem):
    out = subprocess.run(["openssl", "x509", "-noout", "-subject", "-nameopt", "multiline"], input=pem, text=True,
                         capture_output=True, check=True).stdout
    m = re.search(r"commonName\s*=\s*(.+)", out)
    return m.group(1).strip() if m else ""


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else next(p for p in BUNDLES if os.path.exists(p))
    pems = re.findall(r"-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----\n", open(path).read(), re.S)
    found = {}
    for pem in pems:
        s = subject(pem)
        if s in WANTED and s not in found:
            found[s] = pem
    missing = [w for w in WANTED if w not in found]
    if missing:
        sys.exit("not in %s: %s" % (path, ", ".join(missing)))
    with open(OUT, "w") as f:
        f.write('"""Root CA certificates trusted by core/updater.py. Generated by scripts/gen_certs.py: do not edit."""\n')
        f.write("ROOTS = (\n")
        for name in WANTED:
            f.write("    # %s\n    %r,\n" % (name, found[name]))
        f.write(")\n")
    print("wrote %s (%d certificates)" % (os.path.normpath(OUT), len(found)))


if __name__ == "__main__":
    main()
